# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-17 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='name',
            field=models.TextField(max_length=30),
        ),
    ]
