# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20170617_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
